export const typeColors = {
  fire: "bg-red-500 text-white",
  water: "bg-blue-400 text-white",
  grass: "bg-green-500 text-white",
  electric: "bg-yellow-300 text-black",
  ice: "bg-cyan-300 text-black",
  bug: "bg-lime-500 text-black",
  poison: "bg-purple-500 text-white",
  flying: "bg-indigo-300 text-black",
  ground: "bg-yellow-600 text-white",
  dragon: "bg-indigo-800 text-white",
  psychic: "bg-pink-400 text-white",
  fighting: "bg-orange-600 text-white",
  normal: "bg-gray-400 text-black",
  dark: "bg-gray-800 text-white",
  ghost: "bg-purple-800 text-white",
  steel: "bg-gray-400 text-black",
  fairy: "bg-pink-300 text-black",
  rock: "bg-yellow-700 text-white",
};